[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "web-browser"
version = "0.1.0"
description = "Test web browser"
requires-python = ">=3.14"

dependencies = []